<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal; tab-stops: 463.5pt\">IJGC started when a group of parents would like to see their children have more opportunity to play golf in a competitive environment, and at the same time learn more than “just golf”. We have seen in other countries where they have set up organizations to support the golfing bodies to help the development. We want our children to pursue excellence and appreciate the opportunities they receive.<SPAN style=\"mso-spacerun: yes\">&nbsp; </SPAN></P>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal; TEXT-ALIGN: justify; tab-stops: 463.5pt\">Our mission is to establish an organization committed to build opportunities for our children through the enjoyment of golf.<SPAN style=\"mso-spacerun: yes\">&nbsp; </SPAN>We believe that through a sport like golf can provide a solid foundation for the children to prepare for life. We hope that such establishment like us can lead new opportunities in the future for our children.</P>
<P class=MsoNormal style=\"MARGIN: 0in 0in 10pt\"><?xml:namespace prefix = st1 ns = \"urn:schemas-microsoft-com:office:smarttags\" /><st1:place w:st=\"on\"><B style=\"mso-bidi-font-weight: normal\">MISSION</B></st1:place><B style=\"mso-bidi-font-weight: normal\"> STATEMENT: <?xml:namespace prefix = o ns = \"urn:schemas-microsoft-com:office:office\" /><o:p></o:p></B></P>
<TABLE class=MsoNormalTable style=\"BORDER-RIGHT: medium none; BORDER-TOP: medium none; BORDER-LEFT: medium none; BORDER-BOTTOM: medium none; BORDER-COLLAPSE: collapse; mso-border-alt: solid black .5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-border-insideh: .5pt solid black; mso-border-insidev: .5pt solid black\" cellSpacing=0 cellPadding=0 border=1>
<TBODY>
<TR style=\"mso-yfti-irow: 0; mso-yfti-firstrow: yes\">
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: black 1pt solid; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: black 1pt solid; WIDTH: 68.1pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt\" vAlign=top width=91>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\">Organization</P></TD>
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: black 1pt solid; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: #ece9d8; WIDTH: 346.8pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt; mso-border-left-alt: solid black .5pt\" vAlign=top width=462>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\">Indonesian Junior Golf Community (IJGC)</P>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\"><o:p>&nbsp;</o:p></P></TD></TR>
<TR style=\"mso-yfti-irow: 1\">
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: #ece9d8; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: black 1pt solid; WIDTH: 68.1pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt; mso-border-top-alt: solid black .5pt\" vAlign=top width=91>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\">Theme</P></TD>
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: #ece9d8; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: #ece9d8; WIDTH: 346.8pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-top-alt: solid black .5pt\" vAlign=top width=462>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\"><I style=\"mso-bidi-font-style: normal\">Building Excellence for Future Generation<o:p></o:p></I></P>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\"><o:p>&nbsp;</o:p></P></TD></TR>
<TR style=\"mso-yfti-irow: 2; mso-yfti-lastrow: yes\">
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: #ece9d8; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: black 1pt solid; WIDTH: 68.1pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt; mso-border-top-alt: solid black .5pt\" vAlign=top width=91>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\"><st1:City w:st=\"on\"><st1:place w:st=\"on\">Mission</st1:place></st1:City></P></TD>
<TD style=\"BORDER-RIGHT: black 1pt solid; PADDING-RIGHT: 5.4pt; BORDER-TOP: #ece9d8; PADDING-LEFT: 5.4pt; PADDING-BOTTOM: 0in; BORDER-LEFT: #ece9d8; WIDTH: 346.8pt; PADDING-TOP: 0in; BORDER-BOTTOM: black 1pt solid; BACKGROUND-COLOR: transparent; mso-border-alt: solid black .5pt; mso-border-left-alt: solid black .5pt; mso-border-top-alt: solid black .5pt\" vAlign=top width=462>
<P class=MsoNormal style=\"MARGIN: 0in 0in 0pt; LINE-HEIGHT: normal\">IJGC is an organization committed to build opportunities for our children through the enjoyment of golf</P></TD></TR></TBODY></TABLE>